CREATE PROC [FI_SP_ConsBeneficiarioPorIdCliente]
	@IDClIENTE BIGINT
AS
BEGIN
	SELECT 
		[ID],
		[NOME], 
		[CPF],
		[IDCLIENTE]
	FROM 
		[BENEFICIARIOS] WITH(NOLOCK)
	WHERE
		[IDCLIENTE] = @IdCliente
END