//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.WebAtividadeEntrevista.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidateMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidateMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FI.WebAtividadeEntrevista.Language.ValidateMsg", typeof(ValidateMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF informado não é válido.
        /// </summary>
        internal static string MSG01 {
            get {
                return ResourceManager.GetString("MSG01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF informado já se encontra cadastrado.
        /// </summary>
        internal static string MSG02 {
            get {
                return ResourceManager.GetString("MSG02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Beneficiários com CPFs duplicados:.
        /// </summary>
        internal static string MSG03 {
            get {
                return ResourceManager.GetString("MSG03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro efetuado com sucesso.
        /// </summary>
        internal static string MSG04 {
            get {
                return ResourceManager.GetString("MSG04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro alterado com sucesso.
        /// </summary>
        internal static string MSG05 {
            get {
                return ResourceManager.GetString("MSG05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiário com o CPF &apos;{0}&apos; já cadastrado para este cliente.
        /// </summary>
        internal static string MSG06 {
            get {
                return ResourceManager.GetString("MSG06", resourceCulture);
            }
        }
    }
}
